<?php
// $Id$
/**
 * @file
 * Administer Skin Cancer Study participant photo uploads
 */
define('SUBMITTED_BEFORE', 'Yes, this spot has changed since the last photo that I submitted');
//dpm($form);

/**
 * Implements hook_init()
 */
function skincancer_init() {
  drupal_add_js(drupal_get_path('module', 'skincancer') . '/js/upload_form.js'); 
}

/**
 * Implements hook_form_BASE_FORM_ID_alter
 */

function skincancer_form_entityform_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'image_upload_form_validate';
}

function image_upload_form_validate(&$form, &$form_state) {
  $submittedBefore = $form_state['input']['field_skin_submitted_before']['und'];
  $sawProvider = $form_state['input']['field_skin_saw_health_provider']['und'];
  $providerVisit = $form_state['input']['field_skin_provider_visit']['und'][0]['value'];
  if($submittedBefore == SUBMITTED_BEFORE && $sawProvider == NULL) {
    form_set_error('field_skin_saw_health_provider','You need to specify if you saw your health provider');
  }
  if($sawProvider == 'Yes' && $providerVisit == '') {
    form_set_error('field_skin_provider_visit','Please specify what happened when you visited your healthcare provider');
  }
  //dpm($form_state['input']);
}


